### ISSUE TITLE
Update user guide for Bob Wallet

### ISSUE THREAD

**Issue by john-light** [BobWallet/BobWallet#5]
Thank you for working on this software! I would like to help write a user guide for Bob Wallet. I have some questions before I start:

1. Does the user have to keep Bob Wallet open during the mixing process? What happens if they disconnect during the mix?

2. After the mixing completes, the user's bitcoin is divided into multiple addresses. For example, my test transaction was split into nine different addresses. If the user imports their seed into another wallet so they can spend the coins, will combining the UTXOs from these different addresses into a larger transaction deanonymize the user? For example if I mix 1 BTC using Bob Wallet, and it is broken up into ten addresses with 0.1 BTC in each address, then I import the Private Wallet into Electrum and send 0.5 BTC to another address, will that transaction deanonymize me?

3. Is there a minimum or maximum amount of bitcoin that can/must go through the mixer?

4. After using a Public Wallet once, will using the same Public Wallet again link the next mix to the previous mix?

5. I want to publicly announce a specific day and time that people could "meet" online to mix together, to increase the anonymity set of each transaction. Do you think this would be good or bad for privacy? (I say possibly bad because it could alert an attacker about when a good time to launch a Sybil attack might be. But maybe this isn't a risk, I'm not sure so I thought I'd ask.)

**Comment by BobWalletUser** [comment]
1. The user has to keep Bob Wallet open for the mixing process to happen. If they disconnect during the Join stage they are just removed from the round. If they disconnect mid-round then they will be blamed for stopping the round and a new round will start without them. Right now it is less important if a round is stopped since punishments haven't yet been added and rounds are quick. 

2. If they combine multiple outputs in a transaction they can be all linked together and depending how many Bob users were in the round they may be deanonymized. This can also happen if they use the Private Wallet seed in a wallet that queries balances from a 3rd party API. There is a big need for a privacy focused wallet that manages the Private Wallet properly after going through Bob Wallet. Using a full-node or Neutrino light-client is preferred right now.

3. The min/max is set by the coordinator. Currently it only moves 0.0001 tBTC per round for testing purposes and the user can join as many rounds as they want. I can imagine the coordinator would have multiple output tiers so that larger amounts wouldn't take as long.

Example:
Users Public Wallet balance: 1.21 BTC

Round #1: 1.0 BTC output
Round #2: 0.1 BTC output
Round #3: 0.1 BTC output
Round #4: 0.01 BTC output

There could also be a feature where it takes the maximum amount possible from all the users in the round.

Example:
User 1: 1 BTC
User 2: 3 BTC
User 3: 4 BTC

Round #1: 1 BTC output (3 users joined)
Round #2: 2 BTC output (2 users joined)
(User 3 would still have 1 remaining BTC)

4. Possibly. As long as the Public Wallet funding address hasn't been used before or have a change balance then they can not be linked. We could enforce empty funding addresses into the code in the future.

5. The best way to do this may be to include a countdown timer in Bob Wallet to indicate when the next planned round is so that users can maximize participants in a round. It could become common knowledge that Bob Wallet rounds start at a specific time every single day for maximal liquidity. 

To protect against potential Sybil attacks you can run 2 or more Bob Wallets at the same time so that you know the coordinator is not singling out one user. If 1 of your users is not able to join then it may indicate a Sybil attack.

@john-light  Would love to see a Bob Wallet user guide. Let me know where we can help.

**Comment by john-light** [comment]
Thanks @BobWallets these answers are very helpful.

**Comment by BobWallets** [comment]
I just pushed the first working version of the CoinShuffle implimentation. This will change the first 3 steps in the user guide.

1. Tor is no longer necessary. Users can now go directly to https://bobwallet.github.io on any browser.
2. I added a simple "Start" button that auto-generates the Public and Private wallet seeds automatically to make it even easier. If users want to enter their own seeds there is now an "Advanced" button on the welcome screen.

**Comment by john-light** [comment]
In a soundbite, what would you say is the main difference between the mixer used in 0.0.5 and the shufflelink implementation used in 0.1.0 @BobWallets?

**Comment by BobWallets** [comment]
From a users perspective they are exactly the same except now they are not required to use the Tor Browser.

From a technical level the difference is the technique that randomizes the output utxos in a CoinJoin transaction from Blind Signatures (0.5.0) to now CoinShuffle (0.1.0)
